[package]
name = "rust-git"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
sha1 = "0.10.6"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
walkdir = "2"